#!/usr/bin/env bash
# aphotic plugin — install, manage, and run hooks for the plugin system.
# @cmd: plugin
# @cmd.desc: List, install, enable/disable, or remove plugins
# @cmd.group: CONFIG
# @cmd.opt: list [--remote] [--json]  | List installed (or available-remote) plugins
# @cmd.opt: install <name> [--link]   | Install a plugin from APHOTIC_PLUGINS_REPO
# @cmd.opt: enable|disable <name>     | Toggle a plugin without uninstalling it
# @cmd.opt: remove <name>             | Uninstall a plugin
#
# See docs/PLUGIN_SYSTEM.md. A plugin is a directory under
# APHOTIC_PLUGINS_DIR with its own plugin.toml (same "directory +
# manifest" shape as a theme). This file also owns `run-theme-hooks`, the
# one shared implementation of the theme-hook loop called from all three
# theme-apply call sites (cmd_theme.sh here, Themes.qml/Wallpapers.qml,
# and wallswitcher.py) — see _aphotic_plugin_run_theme_hooks below.

_aphotic_plugin_dir() { printf '%s/%s' "$APHOTIC_PLUGINS_DIR" "$1"; }

_aphotic_plugin_describe() {
    local name="$1" dir manifest display desc version caps enabled missing bin
    dir="$(_aphotic_plugin_dir "$name")"
    manifest="${dir}/plugin.toml"
    [[ -f "$manifest" ]] || return 1

    display="$(aphotic_toml_get "$manifest" plugin display_name)"
    desc="$(aphotic_toml_get "$manifest" plugin description)"
    version="$(aphotic_toml_get "$manifest" plugin version)"
    caps="$(aphotic_toml_get_array "$manifest" plugin capabilities | jq -R . | jq -s .)"
    enabled="false"
    aphotic_plugin_is_enabled "$name" && enabled="true"

    missing="[]"
    while IFS= read -r bin; do
        [[ -z "$bin" ]] && continue
        command -v "$bin" >/dev/null 2>&1 || missing="$(jq --arg b "$bin" '. + [$b]' <<<"$missing")"
    done < <(aphotic_toml_get_array "$manifest" requires binaries)

    jq -n \
        --arg name "$name" \
        --arg display_name "${display:-$name}" \
        --arg description "${desc:-}" \
        --arg version "${version:-0.0.0}" \
        --argjson capabilities "${caps:-[]}" \
        --argjson enabled "$enabled" \
        --argjson missing_binaries "$missing" \
        '{name: $name, display_name: $display_name, description: $description, version: $version, capabilities: $capabilities, enabled: $enabled, missing_binaries: $missing_binaries}'
}

_aphotic_plugin_list_installed_json() {
    local name entries=()
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        entries+=("$(_aphotic_plugin_describe "$name")")
    done < <(aphotic_plugin_names)
    printf '%s\n' "${entries[@]:-}" | jq -s 'map(select(. != null))'
}

_aphotic_plugin_list_remote_json() {
    aphotic_require curl || return 1
    curl -fsSL -m 10 "$APHOTIC_PLUGINS_INDEX_URL" 2>/dev/null || echo '{"plugins": []}'
}

# Fire every enabled theme-hook plugin's on_theme_change script, piping
# the current resolved palette (~/.local/state/aphotic/palette.json,
# regenerated by wallust on every theme apply — see wallust.toml's
# `plugin_palette` template) to it on stdin as JSON. Fire-and-forget with
# a timeout: a broken/hanging plugin hook must never block or fail the
# theme switch it's piggybacking on, matching the existing
# papirus-folders/sddm-sync "warn and no-op" precedent in this same
# command group.
_aphotic_plugin_run_theme_hooks() {
    local palette_file="${APHOTIC_STATE_HOME}/palette.json"
    [[ -f "$palette_file" ]] || return 0

    local name dir manifest hook caps
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        aphotic_plugin_is_enabled "$name" || continue

        dir="$(_aphotic_plugin_dir "$name")"
        manifest="${dir}/plugin.toml"
        caps="$(aphotic_toml_get_array "$manifest" plugin capabilities)"
        grep -qx "theme-hook" <<<"$caps" || continue

        hook="$(aphotic_toml_get "$manifest" hooks on_theme_change)"
        [[ -n "$hook" && -x "${dir}/${hook}" ]] || continue

        (
            timeout 5 "${dir}/${hook}" < "$palette_file" >/dev/null 2>&1 \
                || aphotic_warn "plugin '${name}': on_theme_change hook failed or timed out"
        ) &
        disown 2>/dev/null || true
    done < <(aphotic_plugin_names)
}

_aphotic_plugin_install() {
    local name="$1" link="$2" src dest
    [[ -n "$name" ]] || { aphotic_err "usage: aphotic plugin install <name> [--link]"; return 1; }

    src="${APHOTIC_PLUGINS_REPO}/${name}"
    if [[ ! -d "$src" ]] || [[ ! -f "${src}/plugin.toml" ]]; then
        aphotic_err "no plugin '${name}' found under ${APHOTIC_PLUGINS_REPO} — clone/pull the aphotic-plugins repo there first"
        return 1
    fi

    dest="$(_aphotic_plugin_dir "$name")"
    if [[ -e "$dest" ]]; then
        aphotic_err "already installed: ${dest} (remove it first to reinstall)"
        return 1
    fi

    if [[ "$link" == "true" ]]; then
        ln -s "$src" "$dest"
        aphotic_ok "linked ${name} -> ${src}"
    else
        cp -r "$src" "$dest"
        aphotic_ok "installed ${name}"
    fi

    find "$dest" -path "*/hooks/*" -type f -exec chmod +x {} \; 2>/dev/null || true
}

_aphotic_plugin_remove() {
    local name="$1" dest
    [[ -n "$name" ]] || { aphotic_err "usage: aphotic plugin remove <name>"; return 1; }
    dest="$(_aphotic_plugin_dir "$name")"
    [[ -e "$dest" ]] || { aphotic_err "not installed: ${name}"; return 1; }
    rm -rf "$dest"
    aphotic_plugin_set_enabled "$name" true # clear any disabled-state entry
    aphotic_ok "removed ${name}"
}

aphotic_cmd_plugin() {
    local sub="${1:-}"; shift || true

    case "$sub" in
        list)
            local remote="false" as_json="false"
            for arg in "$@"; do
                case "$arg" in
                    --remote) remote="true" ;;
                    --json) as_json="true" ;;
                esac
            done

            aphotic_require jq || return 1

            local data
            if [[ "$remote" == "true" ]]; then
                data="$(_aphotic_plugin_list_remote_json)"
                [[ "$as_json" == "true" ]] && { echo "$data" | jq '.plugins // []'; return 0; }
                echo "$data" | jq -r '(.plugins // [])[] | "\(.name)\t\(.display_name)\t\(.version)\t\(.description)"' | column -t -s $'\t'
            else
                data="$(_aphotic_plugin_list_installed_json)"
                [[ "$as_json" == "true" ]] && { echo "$data"; return 0; }
                if [[ "$(echo "$data" | jq 'length')" -eq 0 ]]; then
                    aphotic_log "no plugins installed — see 'aphotic plugin list --remote'"
                else
                    echo "$data" | jq -r '.[] | "\(.name)\t\(.display_name)\t\(if .enabled then "enabled" else "disabled" end)\t\(.version)"' | column -t -s $'\t'
                fi
            fi
            ;;
        install)
            local name="" link="false"
            for arg in "$@"; do
                case "$arg" in
                    --link) link="true" ;;
                    *) name="$arg" ;;
                esac
            done
            _aphotic_plugin_install "$name" "$link"
            ;;
        enable)
            [[ -n "${1:-}" ]] || { aphotic_err "usage: aphotic plugin enable <name>"; return 1; }
            aphotic_plugin_set_enabled "$1" true && aphotic_ok "enabled ${1}"
            ;;
        disable)
            [[ -n "${1:-}" ]] || { aphotic_err "usage: aphotic plugin disable <name>"; return 1; }
            aphotic_plugin_set_enabled "$1" false && aphotic_ok "disabled ${1}"
            ;;
        remove)
            _aphotic_plugin_remove "${1:-}"
            ;;
        run-theme-hooks)
            # Plumbing subcommand — called from cmd_theme.sh and from
            # QML (Wallpapers.qml/Themes.qml) and wallswitcher.py after
            # wallust finishes, never directly by a user. No args: it
            # reads the already-fresh palette.json itself, see above.
            _aphotic_plugin_run_theme_hooks
            ;;
        -h|--help|"")
            cat <<EOF
Usage: aphotic plugin <list|install|enable|disable|remove> [args]

  list [--remote] [--json]   List installed plugins (or --remote: what's
                              available from APHOTIC_PLUGINS_INDEX_URL)
  install <name> [--link]    Install from a local checkout of
                              aphotic-plugins (APHOTIC_PLUGINS_REPO,
                              default ~/aphotic-plugins). --link symlinks
                              instead of copying, for plugin development.
  enable <name>               Re-enable an installed plugin
  disable <name>               Disable without uninstalling
  remove <name>                Uninstall
EOF
            ;;
        *)
            aphotic_err "unknown plugin subcommand: ${sub}"
            return 1
            ;;
    esac
}
