-- Generated by wallust — do not edit by hand, re-run to regenerate.
-- Uses wallust's native templating mode, not pywal-compat mode: this
-- file is a Lua table literal, and Lua's own curly-brace table syntax
-- would be misread as a pywal substitution token under pywal-compat
-- mode (which treats every single opening brace as a variable start).
-- Native mode only triggers on a double-brace pair, so the literal
-- table braces below pass through untouched.
return {
    background = "{{ background }}",
    foreground = "{{ foreground }}",
    color0  = "{{ color0 }}",
    color1  = "{{ color1 }}",
    color2  = "{{ color2 }}",
    color3  = "{{ color3 }}",
    color4  = "{{ color4 }}",
    color5  = "{{ color5 }}",
    color6  = "{{ color6 }}",
    color7  = "{{ color7 }}",
    color8  = "{{ color8 }}",
    color9  = "{{ color9 }}",
    color10 = "{{ color10 }}",
    color11 = "{{ color11 }}",
    color12 = "{{ color12 }}",
    color13 = "{{ color13 }}",
    color14 = "{{ color14 }}",
}
