const {readFileSync} = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ctx = vm.createContext({});
vm.runInContext(readFileSync(__dirname + '/../Configs/quickshell/aphotic/modules/flow/FlowModel.js', 'utf8'), ctx);
const claim = (id, owner, amount, priority='background') => ({id, owner, resource:'gpu-vram', amount, priority, origin:'dynamic', label:id});
const spec = {'gpu-vram': {label:'VRAM', capacity:100, safetyMargin:0.1, unit:'MiB'}};
let m = ctx.build([claim('a','ai',70),claim('b','gaming',30,'foreground')], spec, {}, {});
assert.equal(m.resources.find(r=>r.key==='gpu-vram').contended, true);
assert.equal(m.workloads[0].key, 'gaming');
assert.equal(m.edges.length, 2);
m = ctx.build([claim('a','ai',200)], {}, {}, {});
assert.equal(m.resources.find(r=>r.key==='gpu-vram').budget, null);
assert.equal(m.resources.find(r=>r.key==='gpu-vram').contended, false);
m = ctx.build([claim('a','ai',90)], spec, {}, {});
assert.equal(m.resources.find(r=>r.key==='gpu-vram').contended, false);
m = ctx.build([claim('a','ai',0),claim('b','gaming',0)], {'gpu-vram':{exclusive:true}}, {}, {});
assert.equal(m.resources.find(r=>r.key==='gpu-vram').contended, true);
m = ctx.build([], {}, {dev:{phase:'monitor',trigger:'project-open'}}, {dev:{label:'Dev'}});
assert.equal(m.workloads[0].claims.length, 0);
assert.match(m.workloads[0].detail, /project-open/);
assert.equal(m.planes.length,4);
assert.equal(m.planes.map(p=>p.key).join(','),'ai,gaming,security,dev');
m = ctx.build(Array.from({length:30},(_,i)=>claim('c'+i,'p'+i,i)), spec, {}, {});
assert.equal(m.workloads.length,8);
assert.equal(m.hiddenWorkloads,22);
assert.ok(m.edges.length<=24);
assert.equal(m.resources.find(r=>r.key==='gpu-vram').total,435);
console.log('Flow model: 15 assertions passed');
m = ctx.build([claim('model','ollama',20)], spec, {ollama:{phase:'idle'}}, {ollama:{label:'Ollama'}});
assert.equal(m.planes[0].phase,'claims active');
assert.equal(m.workloads[0].claims[0].unit,'MiB');
console.log('Ollama AI plane and claim units: passed');
