const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const p = vm.createContext({});
const dir = __dirname + '/../Configs/quickshell/aphotic/services/';
vm.runInContext(fs.readFileSync(dir+'ShelfPolicy.js','utf8'),p);
const plain = x => JSON.parse(JSON.stringify(x));
assert.equal(p.config({},'DP-1').left.enabled,false);
assert.equal(p.config({'DP-1':{left:{enabled:true}}},'DP-2').left.enabled,false);
assert.equal(p.config({'DP-1':{left:{enabled:'yes'}}},'DP-1').left.enabled,false);
assert.deepEqual(plain(p.config({'DP-1':{left:{pinned:['ok','ok',4],tabs:['tab',null]}}},'DP-1').left.pinned),['ok']);
let cfg=p.update({},'DP-1','left',{enabled:true,pinned:['app']},'Monitor');
assert.equal(p.config(cfg,'DP-1').left.enabled,true);
assert.equal(p.config(cfg,'DP-1').description,'Monitor');
assert.equal(p.config(cfg,'DP-1').right.enabled,false);
assert.equal(p.update(cfg,'DP-1','bad',{enabled:true}),null);
assert.deepEqual(plain(p.reconcile(['DP-1/left','DP-2/right'],cfg,['DP-1'])),['DP-1/left']);
assert.equal(p.conflict([{modmask:64,key:'bracketleft',dispatcher:'exec',arg:'user'}],'left'),true);
assert.equal(p.conflict([{modmask:65,key:'bracketleft',dispatcher:'exec',arg:'user'}],'left'),false);
assert.equal(p.conflict([{modmask:64,key:'bracketright',dispatcher:'exec',arg:'qs -c aphotic ipc call shelves toggle right'}],'right'),false);
vm.runInContext(fs.readFileSync(dir+'DockItems.js','utf8'),p);
const entry={id:'app',name:'App',icon:'app'};
const windows=[{appClass:'a',output:'DP-1'},{appClass:'b',output:'DP-1'},{appClass:'c',output:'DP-2'}];
assert.deepEqual(plain(p.group(windows)).map(g=>g.appClass),['a','b','c']);
const items=p.dockItems(['app','missing'],p.group(windows),id=>id==='app'?entry:null,c=>c==='a'||c==='b'?entry:null);
assert.equal(items.length,2); assert.equal(items[0].windows.length,2); assert.equal(items[1].key,'c');
vm.runInContext(fs.readFileSync(dir+'SurfacePolicy.js','utf8'),p);
const extra={'shelf:DP-1:left':{role:'shelf'},'shelf:DP-1:right':{role:'shelf'}};
assert.deepEqual(plain(p.transition(['shelf:DP-1:left'],'shelf:DP-1:right',true,extra).close),[]);
assert.deepEqual(plain(p.transition(['shelf:DP-1:left'],'launcher',true,extra).close),['shelf:DP-1:left']);
console.log('Shelves policy and dock parity: passed');
