title: Aphotic
description: A modular, resource-aware Linux desktop platform.
url: https://t-crypt.github.io
baseurl: "/aphotic-hypr"
markdown: kramdown
highlighter: rouge
permalink: pretty
collections:
  docs:
    output: true
    permalink: /docs/:name/
exclude:
  - tests
  - scripts
  - _wiki
