[theme]
display_name = "Gruvbox"
description = "Warm retro earth tones."

[icons]
papirus_color = "orange"

[wallpaper]
default = "gruvbox-angeljumbo-assassins-creed-origins-cyrene-01-saturation-0.75-color-temperature-7000.png"
