-- Window rules — see https://wiki.hypr.land/Configuring/Basics/Window-Rules/

-- Opacity
hl.window_rule({ name = "opacity-firefox",   match = { class = "^(firefox)$" },              opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-kitty",     match = { class = "^(kitty)$" },                 opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-steam",     match = { class = "^(Steam|steam|steamwebhelper)$" }, opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-spotify",   match = { class = "^(Spotify)$" },               opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-elisa",     match = { class = "^(org.kde.elisa)$" },         opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-code",      match = { class = "^(Code)$" },                  opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-thunar",    match = { class = "^(thunar)$" },                opacity = "0.70 0.70" })
hl.window_rule({ name = "opacity-fileroller",match = { class = "^(file-roller)$" },           opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-nwg-look",  match = { class = "^(nwg-look)$" },              opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-qt5ct",     match = { class = "^(qt5ct)$" },                 opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-discord",   match = { class = "^(discord|WebCord|VencordDesktop)$" }, opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-pavucontrol", match = { class = "^(pavucontrol)$" },         opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-polkit",    match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" }, opacity = "0.80 0.70" })
hl.window_rule({ name = "opacity-telegram",  match = { class = "^(org.telegram.desktop)$" },  opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-rofi",      match = { class = "^(Rofi)$" },                  opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-mako",      match = { class = "^(Mako)$" },                  opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-weather",   match = { title = "^(Weather)$" },               opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-sysmon",    match = { title = "^(System Monitor)$" },        opacity = "0.80 0.80" })

-- Position / floating
hl.window_rule({ name = "float-lutris",       match = { class = "^(lutris)$" },        float = true })
hl.window_rule({ name = "center-lutris",      match = { class = "^(lutris)$" },        move  = "50% 50%" })
hl.window_rule({ name = "float-pavucontrol",  match = { class = "^(pavucontrol)$" },   float = true })
hl.window_rule({ name = "float-fileprogress", match = { class = "file_progress" },     float = true })
hl.window_rule({ name = "float-confirm",      match = { class = "confirm" },           float = true })
hl.window_rule({ name = "float-dialog",       match = { class = "dialog" },            float = true })
hl.window_rule({ name = "float-download",     match = { class = "download" },          float = true })
hl.window_rule({ name = "float-notification", match = { class = "notification" },      float = true })
hl.window_rule({ name = "float-error",        match = { class = "error" },             float = true })
hl.window_rule({ name = "float-splash",       match = { class = "splash" },            float = true })
hl.window_rule({ name = "float-confirmreset", match = { class = "confirmreset" },      float = true })
hl.window_rule({ name = "float-openfile",     match = { title = "Open File" },         float = true })
hl.window_rule({ name = "float-branchdialog", match = { title = "branchdialog" },      float = true })
hl.window_rule({ name = "float-lxappearance", match = { class = "Lxappeara" },         float = true })
hl.window_rule({ name = "float-rofi",         match = { class = "Rofi" },              float = true, no_anim = true })
hl.window_rule({ name = "float-viewnior",     match = { class = "^(Viewnior|viewnior)$" }, float = true })
hl.window_rule({ name = "float-feh",          match = { class = "feh" },               float = true })
hl.window_rule({ name = "float-pavucontrolqt",match = { class = "pavucontrol-qt" },    float = true })
hl.window_rule({ name = "float-filerroller",  match = { class = "file-roller" },       float = true })
