#!/usr/bin/env python3
"""Generate the CLI-Reference wiki section from the @cmd headers.

The CLI in Configs/.local/lib/aphotic/commands/ annotates every command
with `# @cmd:` / `# @cmd.desc` / `# @cmd.group` / `# @cmd.opt` headers.
This script turns those headers into the generated region of the
CLI-Reference wiki page, so the page can be regenerated instead of
maintained by hand.

Usage:
  gen_cli_reference.py [--repo PATH]          print the generated section
  gen_cli_reference.py --check FILE [--repo PATH]
  gen_cli_reference.py --update FILE [--repo PATH]

`--check` and `--update` operate on a wiki CLI-Reference.md: the section
between the aphotic:cli-reference:begin/end markers must match what the
repo generates. `--check` exits 1 on any mismatch; `--update` rewrites the
marked region in place.
"""

import argparse
import pathlib
import re
import sys

BEGIN = "<!-- aphotic:cli-reference:begin -->"
END = "<!-- aphotic:cli-reference:end -->"

GROUP_ORDER = ["CORE", "CONFIG", "LIFECYCLE", "AI", "BUILD", "FUN"]

OPT_RE = re.compile(r"^#\s*@cmd\.opt:\s*(?P<body>.+?)\s*$")
CMD_RE = re.compile(r"^#\s*@cmd:\s*(?P<name>\S+)\s*$")
DESC_RE = re.compile(r"^#\s*@cmd\.desc:\s*(?P<desc>.+?)\s*$")
GROUP_RE = re.compile(r"^#\s*@cmd\.group:\s*(?P<group>\S+)\s*$")


def split_spec_desc(body: str) -> tuple[str, str]:
    """Split an @cmd.opt line on the last pipe outside <choices>.

    The delimiter is the last top-level pipe, so both `<full|dock|taskbar>`
    choice lists and `enable|disable <name>` verb pairs stay in the spec.
    """
    depth = 0
    cut = -1
    for i, ch in enumerate(body):
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth = max(0, depth - 1)
        elif ch == "|" and depth == 0:
            cut = i
    if cut < 0:
        return body.strip(), ""
    return body[:cut].strip(), body[cut + 1 :].strip()


def is_flag(spec: str) -> bool:
    core = spec.strip().lstrip("[").rstrip("]")
    if core.startswith("--"):
        return True
    return re.match(r"^-[^-\s]\s*,\s*--", core) is not None or re.match(r"^-[^-\s]\s+--", core) is not None

def parse_command_file(path: pathlib.Path) -> dict:
    """One cmd_*.sh file into {name, desc, group, verbs, flags}."""
    cmd = {"name": None, "desc": "", "group": "MISC", "verbs": [], "flags": []}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if m := CMD_RE.match(line):
            cmd["name"] = m["name"]
        elif m := DESC_RE.match(line):
            cmd["desc"] = m["desc"]
        elif m := GROUP_RE.match(line):
            cmd["group"] = m["group"].upper()
        elif m := OPT_RE.match(line):
            spec, desc = split_spec_desc(m["body"])
            if is_flag(spec):
                cmd["flags"].append((spec, desc))
            else:
                cmd["verbs"].append((spec, desc))
    return cmd


def collect_commands(repo: pathlib.Path) -> list:
    commands_dir = repo / "Configs" / ".local" / "lib" / "aphotic" / "commands"
    if not commands_dir.is_dir():
        sys.exit(f"error: no commands directory in {repo}")
    commands = []
    for path in sorted(commands_dir.glob("cmd_*.sh")):
        cmd = parse_command_file(path)
        if cmd["name"]:
            commands.append(cmd)
    return commands


def heading(group: str) -> str:
    return " ".join("AI" if w == "ai" else w.capitalize() for w in group.lower().split())


def render_section(commands: list) -> str:
    groups: dict[str, list] = {}
    for cmd in commands:
        groups.setdefault(cmd["group"], []).append(cmd)
    ordered = [g for g in GROUP_ORDER if g in groups]
    ordered += sorted(g for g in groups if g not in GROUP_ORDER)

    lines = [BEGIN]
    lines.append("<!-- Generated by tools/ci/gen_cli_reference.py from the @cmd")
    lines.append("     headers in Configs/.local/lib/aphotic/commands/. Do not edit")
    lines.append("     by hand: re-run the generator and commit the result; the docs")
    lines.append("     drift check compares this region against the repo on every PR. -->")
    for group in ordered:
        lines.append("")
        lines.append(f"## {heading(group)}")
        lines.append("")
        for cmd in sorted(groups[group], key=lambda c: c["name"]):
            lines.append(f"- `aphotic {cmd['name']}` -- {cmd['desc']}")
            for spec, desc in cmd["verbs"]:
                lines.append(f"- `aphotic {cmd['name']} {spec}` -- {desc}")
            for spec, desc in cmd["flags"]:
                lines.append(f"  - `{spec}` -- {desc}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def extract_region(page_text: str) -> str | None:
    if BEGIN not in page_text or END not in page_text:
        return None
    return page_text.split(BEGIN, 1)[1].split(END, 1)[0]


def section_body(section: str) -> str:
    """The generated section without its marker lines."""
    lines = section.strip().splitlines()
    if lines and lines[0] == BEGIN:
        lines = lines[1:]
    if lines and lines[-1] == END:
        lines = lines[:-1]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".", help="repo root (default: current dir)")
    ap.add_argument("--check", metavar="FILE", help="fail unless FILE's marked region matches")
    ap.add_argument("--update", metavar="FILE", help="rewrite FILE's marked region in place")
    args = ap.parse_args()

    repo = pathlib.Path(args.repo).resolve()
    section = render_section(collect_commands(repo))

    if not args.check and not args.update:
        sys.stdout.write(section)
        return 0

    path = pathlib.Path(args.check or args.update)
    if not path.is_file():
        sys.exit(f"error: {path} not found")
    text = path.read_text(encoding="utf-8")

    if args.update:
        region = extract_region(text)
        if region is None:
            body, sep, tail = text.partition("\n\n")
            text = body + "\n\n" + section + tail
        else:
            new_body = section_body(section)
            text = text.replace(BEGIN + region + END, BEGIN + "\n" + new_body + "\n" + END)
        path.write_text(text, encoding="utf-8")
        print(f"updated {path}")
        return 0

    region = extract_region(text)
    if region is None:
        print(f"FAIL {path}: no generated region (run: python3 tools/ci/gen_cli_reference.py --update {path})")
        return 1
    expected = section_body(section)
    actual = region.strip()
    if actual == expected:
        print(f"PASS {path}: CLI reference matches the repo")
        return 0
    print(f"FAIL {path}: CLI reference has drifted from the @cmd headers")
    import difflib

    for line in difflib.unified_diff(
        expected.splitlines(), actual.splitlines(), "generated", "wiki", lineterm=""
    ):
        print(f"  {line}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
